local builtin = require('telescope.builtin')
vim.keymap.set('n', '<leader><leader>f', builtin.find_files, {})
vim.keymap.set('n', '<C-p>', builtin.git_files, {})
vim.keymap.set('n', '<leader><leader>g', builtin.lsp_references, {})
vim.keymap.set('n', '<leader><leader>s', function()
	builtin.grep_string({ search = vim.fn.input("Grep > ") })
end)
